sql_scripts:
  - |
    DO $$
    BEGIN
      IF NOT EXISTS (SELECT FROM pg_catalog.pg_roles WHERE rolname = 'pets_owner') THEN
        CREATE USER pets_owner WITH PASSWORD 'gatostem123';
      END IF;
    END $$;
  - "GRANT ALL PRIVILEGES ON DATABASE pets TO pets_owner;"
  - "CREATE SCHEMA IF NOT EXISTS files;"